insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Blood Money', 2012, 'PG', 106, 'Thriller');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Last Run', 2001, 'R', 102, 'Thriller');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Poltergeist III', 2007, 'G', 125, 'Thriller');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Hangman''s House', 1993, 'G', 138, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Mr. Vampire', 2009, 'G', 141, 'Horror');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Bloody Angels', 1994, 'G', 150, 'Thriller');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Shed No Tears', 1994, 'R', 142, 'Musical');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Bombardier', 2004, 'G', 137, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Skeleton Man', 1998, 'G', 111, 'Action');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Good Man, A (Un buen hombre)', 1996, 'R', 138, 'Crime');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Army of One (Joshua Tree)', 1989, 'G', 101, 'Action');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('For All Mankind', 1998, 'G', 143, 'Documentary');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Nothing But the Night', 2000, 'PG', 104, 'Crime');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Mommy', 1998, 'PG', 127, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Parkland', 1995, 'G', 103, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('13 Sins', 2010, 'R', 131, 'Horror');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Fat Man and Little Boy', 1995, 'G', 148, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Mass Effect: Paragon Lost', 2003, 'G', 114, 'Action');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Naughty Girl', 2004, 'PG', 124, 'Comedy');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Spirited Away', 1976, 'PG', 148, 'Fantasy');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Alexandra (Aleksandra)', 1990, 'PG', 120, 'War');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Wind Will Carry Us, The ', 2010, 'R', 102, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('New Barbarians, The ', 2000, 'G', 112, 'Western');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Broadway Rhythm', 1988, 'G', 130, 'Musical');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Lazybones', 1988, 'G', 144, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Shadow, The', 2011, 'R', 126, 'Adventure');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Cops', 2002, 'G', 150, 'Comedy');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Married Life', 2013, 'PG', 129, 'Romance');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Day the Fish Came Out, The', 2011, 'G', 148, 'Comedy');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Raiders From Beneath the Sea', 2007, 'PG', 144, 'Crime');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('China Lake Murders, The', 2003, 'R', 114, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Black Mask (Hak hap)', 1993, 'R', 128, 'Adventure');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Never Been Kissed', 2004, 'G', 122, 'Romance');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Axed', 1996, 'G', 112, 'Thriller');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Flame and the Arrow, The', 2003, 'PG', 122, 'Romance');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Madhouse', 1992, 'G', 116, 'Mystery');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('My Name Is Joe', 1998, 'R', 137, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('I Was Born, But... ', 2012, 'PG', 107, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('No End in Sight', 1990, 'R', 131, 'Documentary');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('So Proudly We Hail!', 2009, 'PG', 102, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('King Lear (Korol Lir)', 2012, 'G', 138, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('West Point Story, The', 1993, 'R', 119, 'Comedy');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Working Girl', 1995, 'R', 113, 'Comedy');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('East is East', 2013, 'G', 117, 'Comedy');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Screwed in Tallinn ', 1993, 'R', 108, 'Comedy');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Stalag 17', 1992, 'R', 123, 'War');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Piano, The', 1997, 'R', 142, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Grand Amour, Le', 2009, 'R', 125, 'Comedy');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Thin Red Line, The', 2012, 'G', 111, 'Action');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Raise Your Voice', 1990, 'R', 146, 'Romance');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Bullitt', 1992, 'R', 107, 'Action');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Legionnaire', 1991, 'G', 132, 'Action');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Queen of the Mountains', 2011, 'G', 119, 'Action');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Kwaidan (Kaidan)', 1989, 'PG', 140, 'Horror');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Point, The', 2007, 'PG', 119, 'Animation');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Bolt', 2011, 'R', 123, 'Action');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Out to Sea', 2012, 'PG', 125, 'Comedy');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Black Death', 1997, 'R', 150, 'Adventure');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Wise Blood', 2013, 'G', 146, 'Comedy');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Kill Me Now', 2011, 'R', 111, 'Comedy');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Fear', 1998, 'G', 142, 'Horror');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Batman: Year One', 2003, 'R', 150, 'Action');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Rabid', 2010, 'PG', 113, 'Horror');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Fairly Odd Christmas, A', 2010, 'PG', 103, 'Children');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Zoolander', 1989, 'G', 117, 'Comedy');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Layer Cake', 2005, 'PG', 121, 'Crime');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('The Pacific', 1999, 'PG', 101, 'Action');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Mammoth (Mammut)', 2008, 'PG', 141, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Rachel Papers, The', 1993, 'R', 113, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Forgotten One, The', 2004, 'R', 143, 'Thriller');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Dead Man''s Bluff', 1996, 'R', 136, 'Action');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Short Game, The', 1989, 'R', 137, 'Documentary');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Little Monsters', 1997, 'R', 145, 'Comedy');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Mary Reilly', 1993, 'R', 109, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Kill Your Darlings', 2001, 'R', 147, 'Crime');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Blood on the Sun', 2011, 'PG', 143, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Limey, The', 1986, 'PG', 108, 'Crime');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Vagabond (Sans toit ni loi)', 2005, 'R', 133, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('I Could Go on Singing', 1986, 'R', 107, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Korso', 1991, 'PG', 145, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Back In Action', 1995, 'G', 117, 'Action');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Cool as Ice', 1992, 'G', 105, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('The Swedish Moment', 1998, 'G', 108, 'Comedy');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Purple Rose of Cairo, The', 2011, 'R', 115, 'Comedy');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Coma', 2005, 'G', 145, 'Thriller');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Slow Burn', 2012, 'PG', 122, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Illuminata', 2008, 'PG', 126, 'Comedy');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Bulldog Drummond Escapes', 2005, 'PG', 107, 'Adventure');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Rack, The', 2001, 'PG', 146, 'War');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Earth', 2002, 'G', 130, 'War');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Rock ''n'' Roll Nightmare', 2009, 'G', 108, 'Fantasy');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Skins', 1995, 'R', 110, 'Crime');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Baby Boom', 2003, 'G', 121, 'Comedy');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Times Square', 1999, 'PG', 114, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Blood & Donuts', 2009, 'G', 142, 'Comedy');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Invictus', 2010, 'PG', 147, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Blue Swallow (Cheong yeon)', 1995, 'G', 105, 'Drama');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('No Way to Treat a Lady', 2003, 'R', 143, 'Thriller');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Viy', 2011, 'G', 119, 'Thriller');
insert into tblFilms (title, ReleaseYear, rating, duration, genre) values ('Daisies (Sedmikrasky)', 2004, 'G', 101, 'Drama');
